details: "darker"
foreground: "#FFFFFF"
background: "#1B1B1B"
accent: "#5AC8F5"
terminal_colors:
  normal:
    white: "#FFFFFF"
    yellow: "#FFD60A"
    blue: "#0B84FF"
    magenta: "#BF5AF2"
    black: "#FFFFFF"
    cyan: "#5AC8F4"
    green: "#32D74B"
    red: "#FF453A"
  bright:
    white: "#FFFFFF"
    yellow: "#FFD60A"
    blue: "#0B84FF"
    magenta: "#BF5AF2"
    black: "#FFFFFF"
    cyan: "#5AC8F4"
    green: "#32D74B"
    red: "#FF453A"
