details: "lighter"
foreground: "#1A1A1A"
background: "#FFFFFF"
accent: "#55BEF0"
terminal_colors:
  normal:
    white: "#FFFFFF"
    yellow: "#FFCC00"
    blue: "#007AFF"
    magenta: "#AF52DE"
    black: "#1A1A1A"
    cyan: "#54BEF0"
    green: "#28CD41"
    red: "#FF3B30"
  bright:
    white: "#FFFFFF"
    yellow: "#FFCC00"
    blue: "#007AFF"
    magenta: "#AF52DE"
    black: "#1A1A1A"
    cyan: "#54BEF0"
    green: "#28CD41"
    red: "#FF3B30"
