details: "lighter"
foreground: "#1A1A1A"
background: "#F7F7F7"
accent: "#55BEF0"
terminal_colors:
  normal:
    white: "#1A1A1A"
    yellow: "#FFCC00"
    blue: "#1A1A1A"
    magenta: "#1A1A1A"
    black: "#1A1A1A"
    cyan: "#1A1A1A"
    green: "#28CD41"
    red: "#FF3B30"
  bright:
    black: "#8e8e8e"
    red: "#ffc4bd"
    yellow: "#fefdd5"
    magenta: "#ffb1fe"
    cyan: "#e5e6fe"
    white: "#feffff"
    green: "#d6fcb9"
    blue: "#c1e3fe"
