[style.description]
foreground = "blue"
italic = true

[style.example_text]
foreground = "blue"
bold = true

[style.command_name]
foreground = "green"

[style.example_code]
foreground = "purple"

[style.example_variable]
foreground = "purple"
underline = true

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 48
